name: Build and deploy PowerBI Assessment App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flask msal requests gunicorn

      - name: List installed packages
        run: pip list

      - name: Create templates directory if it doesn't exist
        run: |
          mkdir -p templates
          ls -la templates

      - name: Prepare deployment package
        run: |
          # Create the deployment directory
          mkdir -p deployment
          
          # Copy application files
          cp -r app.py requirements.txt wsgi.py deployment/
          
          # Create templates directory in deployment and copy templates
          mkdir -p deployment/templates
          cp -r templates/* deployment/templates/
          
          # Check the deployment structure
          ls -la deployment
          ls -la deployment/templates
          
          # Create the zip file
          cd deployment
          zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip deployment package
        run: |
          mkdir -p extracted
          unzip release.zip -d extracted
          ls -la extracted
          ls -la extracted/templates || echo "Templates directory not found"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04EF23197AD948579922CE8C9B130C48 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BBDDA4DD81B044348995B693D090179E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_92A65ADEBACC481BAB910098D935C71D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'powerbi-assessment-app'
          slot-name: 'Production'
          package: './extracted'
          startup-command: 'gunicorn --bind=0.0.0.0:8000 --timeout=120 --access-logfile=- --error-logfile=- wsgi:application'
