name: Build and deploy PowerBI Assessment App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install gunicorn

      - name: Create wsgi.py
        run: |
          echo "from app import app as application" > wsgi.py
          echo "if __name__ == '__main__':" >> wsgi.py
          echo "    application.run()" >> wsgi.py

      - name: Prepare deployment package
        run: |
          mkdir -p ${{ github.workspace }}/deployment
          cp -r ${{ github.workspace }}/* ${{ github.workspace }}/deployment/
          cd ${{ github.workspace }}/deployment
          rm -rf .git .github venv
          zip -r ${{ github.workspace }}/release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: ${{ github.workspace }}/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip deployment package
        run: |
          unzip release.zip
          ls -la

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04EF23197AD948579922CE8C9B130C48 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BBDDA4DD81B044348995B693D090179E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_92A65ADEBACC481BAB910098D935C71D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'powerbi-assessment-app'
          slot-name: 'Production'
          startup-command: 'gunicorn --bind 0.0.0.0:8000 wsgi:application'
